---
title: "Benchmarking scry methods with DelayedArray backends"
author: "Stephanie Hicks"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  BiocStyle::html_document:
    toc: false
<!-- vignette: > -->
<!--   %\VignetteEngine{knitr::knitr} -->
<!--   %\VignetteIndexEntry{Benchmarking scry methods with DelayedArray backends} -->
<!--   %\usepackage[UTF-8]{inputenc} -->
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
suppressPackageStartupMessages({
  library(here)
  library(readr)
  library(ggplot2)
  library(dplyr)
  library(tidyr)
})
```

```{r}
if(!file.exists(here("figures"))){
  dir.create(here("figures"))
}
```


# Time

```{r}
my_files <- list.files(here("output_time"))

time_table <- NULL
for (i in (1:length(my_files))){
  tmp_table <- read_csv(here("output_time", my_files[i]))
  time_table <- rbind(time_table, tmp_table)
}
time_table
```

```{r}
time_table <- tidyr::pivot_longer(time_table, c(null, pca), names_to = "phases", values_to = "time")
time_table
```


```{r}
p1 <- time_table %>% 
  unite(fam_model_type, fam:model_type, sep="_") %>%
  ggplot(aes(x = n_obs, y = time/60, color = data_type)) + 
  geom_line() + 
  geom_point() +
  scale_y_log10() + 
  facet_grid(fam_model_type ~ phases) + 
  xlab("number of cells") + 
  ylab("time (mins)") 
p1
```

```{r}
pdf(here("figures", "time.pdf"), width = 8, height = 4)
print(p1)
dev.off()
```

## Notes 

For `binomial_deviance`, I kept getting this error in the `runPCA()` step. So it's not included here. 

```
Error in if (tol * ans$d[1] < eps) warning("convergence criterion below machine epsilon") : 
  missing value where TRUE/FALSE needed
Calls: runPCA ... runSVD -> do.call -> <Anonymous> -> do.call -> <Anonymous>
In addition: Warning message:
In sqrt(2 * (term1 + term2)) : NaNs produced
Execution halted
```


# Memory 

```{r}
my_files <- list.files(here("output_mem"))

mem_table <- NULL
for (i in (1:length(my_files))){
  tmp_table <- read_csv(here("output_mem", my_files[i]))
  mem_table <- rbind(mem_table, tmp_table)
}
mem_table
```



```{r}
p1 <- mem_table %>% 
  unite(fam_model_type, fam:model_type, sep="_") %>%
  ggplot(aes(x = n_obs, y = max_mem, color = data_type)) + 
  geom_line() +
  geom_point() + 
  scale_y_log10() + 
  facet_grid(fam_model_type ~ .) + 
  ylab("max_mem (GB)") + 
  ggtitle(label="Memory usage for nullResiduals() and runPCA() combined")
p1
```

```{r}
pdf(here("figures", "mem.pdf"), width = 6, height = 5)
print(p1)
dev.off()
```

